/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "crawler_constants.h"

namespace server { namespace pose_label {

const crawlerConstants g_crawler_constants;

crawlerConstants::crawlerConstants() {
}

}} // namespace

