/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pose_label_constants.h"

namespace server { namespace pose_label {

const pose_labelConstants g_pose_label_constants;

pose_labelConstants::pose_labelConstants() {
}

}} // namespace

