/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pose_label_CONSTANTS_H
#define pose_label_CONSTANTS_H

#include "pose_label_types.h"

namespace server { namespace pose_label {

class pose_labelConstants {
 public:
  pose_labelConstants();

};

extern const pose_labelConstants g_pose_label_constants;

}} // namespace

#endif
